DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typname = 'statuses'
  ) THEN
    CREATE TYPE statuses AS ENUM ('NEW','IN_PROGRESS','DONE');
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS Tasks (
id SERIAL PRIMARY KEY,
title VARCHAR(30) NOT NULL,
status statuses NOT NULL DEFAULT 'NEW',
created_at TIMESTAMP NOT NULL DEFAULT NOW()
);